# Generated by Django 4.2.5 on 2023-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_auto_20230923_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_of_products',
            new_name='qty_of_products',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='types',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
